# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_binfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgBinFile(object):
    def setupUi(self, dlgBinFile):
        dlgBinFile.setObjectName("dlgBinFile")
        dlgBinFile.resize(692, 315)
        self.label = QtWidgets.QLabel(dlgBinFile)
        self.label.setGeometry(QtCore.QRect(43, 65, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.edtBtType = QtWidgets.QLineEdit(dlgBinFile)
        self.edtBtType.setGeometry(QtCore.QRect(138, 68, 431, 31))
        self.edtBtType.setObjectName("edtBtType")
        self.label_2 = QtWidgets.QLabel(dlgBinFile)
        self.label_2.setGeometry(QtCore.QRect(22, 10, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnBtType = QtWidgets.QPushButton(dlgBinFile)
        self.btnBtType.setGeometry(QtCore.QRect(589, 69, 71, 28))
        self.btnBtType.setObjectName("btnBtType")
        self.label_3 = QtWidgets.QLabel(dlgBinFile)
        self.label_3.setGeometry(QtCore.QRect(26, 127, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnVoiceType = QtWidgets.QPushButton(dlgBinFile)
        self.btnVoiceType.setGeometry(QtCore.QRect(588, 134, 71, 28))
        self.btnVoiceType.setObjectName("btnVoiceType")
        self.edtVoiceType = QtWidgets.QLineEdit(dlgBinFile)
        self.edtVoiceType.setGeometry(QtCore.QRect(137, 133, 431, 31))
        self.edtVoiceType.setObjectName("edtVoiceType")
        self.btnDemoType = QtWidgets.QPushButton(dlgBinFile)
        self.btnDemoType.setGeometry(QtCore.QRect(588, 199, 71, 28))
        self.btnDemoType.setObjectName("btnDemoType")
        self.label_4 = QtWidgets.QLabel(dlgBinFile)
        self.label_4.setGeometry(QtCore.QRect(26, 192, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.edtDemoType = QtWidgets.QLineEdit(dlgBinFile)
        self.edtDemoType.setGeometry(QtCore.QRect(137, 198, 431, 31))
        self.edtDemoType.setObjectName("edtDemoType")
        self.btnOK = QtWidgets.QPushButton(dlgBinFile)
        self.btnOK.setGeometry(QtCore.QRect(214, 262, 93, 28))
        self.btnOK.setObjectName("btnOK")
        self.btnCancel = QtWidgets.QPushButton(dlgBinFile)
        self.btnCancel.setGeometry(QtCore.QRect(360, 263, 93, 28))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(dlgBinFile)
        QtCore.QMetaObject.connectSlotsByName(dlgBinFile)

    def retranslateUi(self, dlgBinFile):
        _translate = QtCore.QCoreApplication.translate
        dlgBinFile.setWindowTitle(_translate("dlgBinFile", "Bin文件选择"))
        self.label.setText(_translate("dlgBinFile", "B T类型:"))
        self.label_2.setText(_translate("dlgBinFile", "请选择对应的BIN文件类型:"))
        self.btnBtType.setText(_translate("dlgBinFile", "..."))
        self.label_3.setText(_translate("dlgBinFile", "Voice类型:"))
        self.btnVoiceType.setText(_translate("dlgBinFile", "..."))
        self.btnDemoType.setText(_translate("dlgBinFile", "..."))
        self.label_4.setText(_translate("dlgBinFile", "Demo类型:"))
        self.btnOK.setText(_translate("dlgBinFile", "确定"))
        self.btnCancel.setText(_translate("dlgBinFile", "取消"))
