# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diaHelp(object):
    def setupUi(self, diaHelp):
        diaHelp.setObjectName("diaHelp")
        diaHelp.resize(446, 311)
        self.label = QtWidgets.QLabel(diaHelp)
        self.label.setGeometry(QtCore.QRect(40, 23, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(diaHelp)
        self.label_2.setGeometry(QtCore.QRect(40, 56, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(diaHelp)
        self.label_3.setGeometry(QtCore.QRect(39, 90, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(diaHelp)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(diaHelp)
        self.label_5.setGeometry(QtCore.QRect(43, 185, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btnOK = QtWidgets.QPushButton(diaHelp)
        self.btnOK.setGeometry(QtCore.QRect(167, 265, 93, 28))
        self.btnOK.setObjectName("btnOK")
        self.lblLogo = QtWidgets.QLabel(diaHelp)
        self.lblLogo.setGeometry(QtCore.QRect(312, 40, 72, 61))
        self.lblLogo.setObjectName("lblLogo")
        self.label_6 = QtWidgets.QLabel(diaHelp)
        self.label_6.setGeometry(QtCore.QRect(39, 124, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(diaHelp)
        self.label_7.setGeometry(QtCore.QRect(43, 206, 381, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(diaHelp)
        self.label_8.setGeometry(QtCore.QRect(43, 229, 361, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(diaHelp)
        QtCore.QMetaObject.connectSlotsByName(diaHelp)

    def retranslateUi(self, diaHelp):
        _translate = QtCore.QCoreApplication.translate
        diaHelp.setWindowTitle(_translate("diaHelp", "Dialog"))
        self.label.setText(_translate("diaHelp", "1:选择->配置->串口类型"))
        self.label_2.setText(_translate("diaHelp", "2:选择->配置->选择文件"))
        self.label_3.setText(_translate("diaHelp", "3:选择->协议->C模块协议"))
        self.label_4.setText(_translate("diaHelp", "注: 1.C模块协议烧入速度比Python协议要快数分钟"))
        self.label_5.setText(_translate("diaHelp", " 2.BT类型->选择与(BT_FW_*.bin)对应的文件"))
        self.btnOK.setText(_translate("diaHelp", "确定"))
        self.lblLogo.setText(_translate("diaHelp", "TextLabel"))
        self.label_6.setText(_translate("diaHelp", "4:选择->类型->要升级的文件类型"))
        self.label_7.setText(_translate("diaHelp", " 3.Voice类型->选择与(Combined_*.bin)对应的文件"))
        self.label_8.setText(_translate("diaHelp", " 4.Demo类型->选择与(Demo_*.bin)对应的文件"))
